import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { cn } from "@/lib/utils";

import { ConvexClientProvider } from "@/components/convex-client-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ConvexAuthNextjsServerProvider>
    <html lang="en" className={cn("h-full font-sans", GeistSans.variable)}>
        <body className={cn("min-h-screen", inter.className)}>
          <ConvexClientProvider>
            {children}
          </ConvexClientProvider>
        </body>
    </html>
    </ConvexAuthNextjsServerProvider>
  );
}
